




#include "nsISupports.idl"

[scriptable, uuid(9246cad6-926a-4c17-88b0-ecba8078d143)]
interface nsIToolkitShellService : nsISupports
{
  





  boolean isDefaultApplication();
};

%{ C++
#define NS_TOOLKITSHELLSERVICE_CONTRACTID "@mozilla.org/toolkit/shell-service;1"
%}
