







#include "nsISupports.idl"              




interface mozIDOMWindow;
interface nsIDocShell;

webidl Element;
webidl Range;




[scriptable, uuid(ae501e28-c57f-4692-ac74-410e1bed98b7)]
interface nsITypeAheadFind : nsISupports
{
  

  


  void init(in nsIDocShell aDocShell);


  

  

  unsigned short find(in AString aSearchString,
                      in boolean aLinksOnly,
                      in unsigned long aMode,
                      in boolean aDontIterateFrames);

  
  Range getFoundRange();


  

  

  void setDocShell(in nsIDocShell aDocShell);

  

  void setSelectionModeAndRepaint(in short toggle);

  


  void collapseSelection();

  
  boolean isRangeVisible(in Range aRange, in boolean aMustBeInViewPort);

  
  boolean isRangeRendered(in Range aRange);

  

  readonly attribute AString searchString;
                                        
  attribute boolean caseSensitive;      
  attribute boolean matchDiacritics;    
  attribute boolean entireWord;         
  readonly attribute Element foundLink;
                                        
  readonly attribute Element foundEditable;
                                        
  readonly attribute mozIDOMWindow currentWindow;
                                        


  

  
  const unsigned long FIND_INITIAL = 0;
  const unsigned long FIND_NEXT = 1;
  const unsigned long FIND_PREVIOUS = 2;
  const unsigned long FIND_FIRST = 3;
  const unsigned long FIND_LAST = 4;

  
  const unsigned short FIND_FOUND    = 0;
                                        
  const unsigned short FIND_NOTFOUND = 1;
                                        
  const unsigned short FIND_WRAPPED  = 2;
                                        
  const unsigned short FIND_PENDING  = 3;
                                        


  

};



