



WPT_FINGERPRINT = 'g5u/rgCX+jMZemQEEl+2uLu914gIvY4DaUkrIwXbqJo='


SXG_WPT_FINGERPRINT = '0Rt4mT6SJXojEMHTnKnlJ/hBKMBcI4kteBlhR1eTTdk='

IGNORE_CERTIFICATE_ERRORS_SPKI_LIST = [
    WPT_FINGERPRINT,
    SXG_WPT_FINGERPRINT
]
