



WPT_FINGERPRINT = 'RtijU6YWXgOa1vlrp14TaeWmmoWCao6Tmbqf6ybUV0E='


SXG_WPT_FINGERPRINT = '0Rt4mT6SJXojEMHTnKnlJ/hBKMBcI4kteBlhR1eTTdk='

IGNORE_CERTIFICATE_ERRORS_SPKI_LIST = [
    WPT_FINGERPRINT,
    SXG_WPT_FINGERPRINT
]
