





Classes = [
    {
        'cid': '{4e22d3ea-aaa2-436e-ada4-9247de57d367}',
        'contract_ids': ['@mozilla.org/system-proxy-settings;1'],
        'type': 'nsWindowsSystemProxySettings',
    },
]
