





Classes = [
    {
        'cid': '{0fa3158c-d5a7-43de-9181-a285e74cf1d4}',
        'contract_ids': ['@mozilla.org/system-proxy-settings;1'],
        'type': 'nsUnixSystemProxySettings',
    },
]
