




#include "nsISupports.idl"
interface nsIFile;








[scriptable, uuid(048e5ca1-0eb7-4bb1-a9a2-a36f7d4e0e3c)]
interface nsIProfileStartup : nsISupports
{
  




  readonly attribute nsIFile directory;

  



  void doStartup();
};








[scriptable, uuid(3df284a5-2258-4d46-a664-761ecdc04c22)]
interface nsIProfileMigrator : nsISupports
{
  



















  void migrate(in nsIProfileStartup aStartup, in ACString aKey,
               [optional] in AUTF8String aProfileName);
};

%{C++
#define NS_PROFILEMIGRATOR_CONTRACTID "@mozilla.org/toolkit/profile-migrator;1"
%}
